<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.0.0</Version>
		<Authors>Felix Leistner</Authors>
		<Company>Little Phoenix</Company>
		<Copyright>2022</Copyright>
		<AssemblyName>Serilog.ConsoleTest</AssemblyName>
		<RootNamespace>Serilog.ConsoleTest</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Autofac" Version="8.1.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.0" />
		<PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
		<PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
		<PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
		<PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
		<PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Serilog.File\Serilog.File.csproj" />
	  <ProjectReference Include="..\Serilog.Seq\Serilog.Seq.csproj" />
	  <ProjectReference Include="..\Serilog\Serilog.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="serilog.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>