<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net10.0;net462</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture.AutoMoq" Version="4.18.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="nunit" Version="4.4.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
		<PackageReference Include="Serilog.Formatting.Compact.Reader" Version="4.0.0" />
		<PackageReference Include="System.Reactive.Linq" Version="6.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Serilog.Seq\Serilog.Seq.csproj" />
	</ItemGroup>

</Project>