# ╔════════════════════════╗
# ║ PHOENIX Release v1.1.0 ║
# ╚════════════════════════╝
name: Release

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  release:
    permissions:
      contents: write
      id-token: write
      checks: write
    uses: LittleGitPhoenix/Automation.Workflows/.github/workflows/release-library.yml@v1
    secrets:
      NUGET_USER: ${{ secrets.NUGET_USER }}
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}